[Speculation] Bug fixing in speculation integration tests (#616)
When running the integration tests with speculation using the following
command:
```
$ python3 tools/integration/run_spec_integration.py single_loop
```
the flow failed with either one of the following errors:
1) Failed to apply standard transformations to cf:
error: failed to parse MemDependenceArrayAttr parameter 'dependencies'
which is to be a
`::llvm::ArrayRef<::dynamatic::handshake::MemDependenceAttr>`
memref.store %c1_i32, %arg1[%8] {handshake.deps =
#handshake<deps[<"store0" (0)>]>, handshake.name = "store0"} :
memref<200xi32>

2) Failed to place simple buffers

# Cause of the 1:
This error occures beacause the syntax of the `cf.mlir` file has
changed.

Since the `cf` file used for speculation differs from the one generated
by the standard Dynamatic flow, the outdated syntax caused a failure.

To fix this, I manually updated the syntax in the speculative `cf.mlir`
files.
This issue appeared in four benchmarks:
- single_loop
- nested_loop
- loop_path
- if_convert

# Cause of the 2:
The reason for the second one is that the `run_spec_integration.py`
script used to employ the following json file:
```
timing_model = DYNAMATIC_ROOT / "data" / "components-flopoco.json"
```
which is no longer available and it should be changed into:
```
timing_model = DYNAMATIC_ROOT / "data" / "components.json"
```
Updating this path resolves the buffer placement failure.

# Additional issue
Even after applying the above two simple fixes, the `subdiag` and
`subdiag_fast` tests crashed with the following error:
```
Added speculative units
No operation named "load5" exists
Failed to export Handshake
```
The reason for this issue lies in the `buffer.json` files in the
respective directories of these kernels. Both files specifically
reference a "load5" operator that does not exist in th IR. By taking a
look at the IR, I changed that into "load2" for both of these kernels,
and ran the tests.